[package]
name = "openai"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
dotenvy = "0.15"

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.openai_proc_macros]
path = "openai_proc_macros"

[dependencies.openai_utils]
path = "openai_utils"

[dev-dependencies.tokio]
version = "1.24"
features = ["full"]

[build-dependencies]
dotenvy = "0.15"

[workspace]
exclude = ["examples"]

[workspace.package]
version = "1.0.0-alpha"
authors = ["valentinegb"]
edition = "2021"
repository = "https://github.com/valentinegb/openai"
license = "AGPL-3.0-only"
