[package]
name = "openai"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "An unofficial Rust library for the OpenAI API."
repository.workspace = true
license.workspace = true
keywords = ["ai", "high-level", "machine-learning"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
dotenvy = "0.15"
derive_builder = "0.12"

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.openai_proc_macros]
path = "openai_proc_macros"

[dependencies.openai_bootstrap]
path = "openai_bootstrap"

[dev-dependencies.tokio]
version = "1.25"
features = ["full"]

[build-dependencies]
dotenvy = "0.15"

[workspace]
exclude = ["examples"]

[workspace.package]
version = "1.0.0-alpha.3"
authors = ["valentinegb"]
edition = "2021"
repository = "https://github.com/valentinegb/openai"
license = "AGPL-3.0-only"
