name: crates.io

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Publish `openai_bootstrap`
        continue-on-error: true
        run: cargo publish --token ${CRATES_TOKEN} -p openai_bootstrap
      - name: Publish `openai_proc_macros`
        continue-on-error: true
        run: cargo publish --token ${CRATES_TOKEN} -p openai_proc_macros
      - name: Publish `openai`
        continue-on-error: true
        run: cargo publish --token ${CRATES_TOKEN} -p openai
      - name: Build docs
        run: cargo doc --verbose
      - name: Create docs index file
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=openai\">" > target/doc/index.html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc
  deploy:
    needs: publish
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
