name: crates.io

on:
  release:
    types: [published]


env:
  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Publish `openai_bootstrap`
        continue-on-error: true
        run: cargo publish --token ${CRATES_TOKEN} -p openai_bootstrap
      - name: Publish `openai_proc_macros`
        continue-on-error: true
        run: cargo publish --token ${CRATES_TOKEN} -p openai_proc_macros
      - name: Publish `openai`
        continue-on-error: true
        run: cargo publish --token ${CRATES_TOKEN} -p openai
